{
 "title": "MySQL Router",
 "description": "https://github.com/rluisr/mysqlrouter_exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(mysqlrouter_router_status, hostname)"
   },
   {
    "name": "cluster",
    "query": "label_values(mysqlrouter_metadata, name)"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysqlrouter_router_status{hostname=\"$host\"}"
    }
   ]
  },
  {
   "type": "table",
   "description": "Nodes of cluster",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "mysqlrouter_metadata_config_node{cluster_name=\"$cluster\", router_host=\"$host\"}"
    }
   ]
  },
  {
   "title": "$host - Route Health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "mysqlrouter_route_health{name=~\"$cluster.*\", router_hostname=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$host - Route Active Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysqlrouter_route_active_connections{name=~\"$cluster.*\", router_hostname=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$host - Route byte from/to server",
   "type": "graph",
   "description": "If route have no connections, There is no data.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mysqlrouter_route_connections_byte_from_server{name=~\"$cluster.*\", router_hostname=\"$host\"}",
     "legendFormat": "from_server {{name}} - {{source_address}} -> {{destination_address}}"
    },
    {
     "expr": "mysqlrouter_route_connections_byte_to_server{name=~\"$cluster.*\", router_hostname=\"$host\"}",
     "legendFormat": "to_server {{name}} - {{destination_address}} -> {{source_address}}"
    }
   ]
  },
  {
   "title": "$host - Route Blocked Hosts",
   "type": "bargauge",
   "description": "Each routing has its own list of blocked hosts. Blocked clients receive the MySQL Server error 1129 code with a slightly different error message: \"1129: Too many connection errors from fail.example.com\". The Router logs contain extra information for blocked clients, such as: INFO [...] 1 authentication errors for fail.example.com (max 100) WARNING [...] blocking client host fail.example.com",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "mysqlrouter_route_blocked_hosts{name=~\"$cluster.*\", router_hostname=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$host - All Connections Information",
   "type": "table",
   "description": "Click table column",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "mysqlrouter_route_connections_byte_to_server{name=~\"$cluster.*\", router_hostname=\"$host\"}"
    },
    {
     "expr": "mysqlrouter_route_connections_byte_from_server{name=~\"$cluster.*\", router_hostname=\"$host\"}"
    },
    {
     "expr": "mysqlrouter_route_connections_time_connected_to_server{name=~\"$cluster.*\", router_hostname=\"$host\"}"
    },
    {
     "expr": "mysqlrouter_route_connections_time_last_received_from_server{name=~\"$cluster.*\", router_hostname=\"$host\"}"
    },
    {
     "expr": "mysqlrouter_route_connections_time_last_sent_to_server{name=~\"$cluster.*\", router_hostname=\"$host\"}"
    },
    {
     "expr": "mysqlrouter_route_connections_time_started{name=~\"$cluster.*\", router_hostname=\"$host\"}"
    }
   ]
  }
 ]
}