{
 "title": "CloudWatch Exporter",
 "description": "Dashboard for Amazon CloudWatch exporter API calls: https://github.com/prometheus/cloudwatch_exporter",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Potential monthly bill (projection based on the last 2 weeks with 30% buffer)",
   "type": "gauge",
   "description": "Assumption of $10 per 1M calls",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(increase(cloudwatch_requests_total[2w])) / 14) * 30 * 10 * 1.3 / 1000000"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_name=\"prometheus-cloudwatch-exporter\"} / (1024 * 1024)",
     "legendFormat": "Memory Usage (in MB)"
    }
   ]
  },
  {
   "title": "API Call count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cloudwatch_requests_total[5m])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum(increase(cloudwatch_requests_total[5m]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "API Call Count - Comparison",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(cloudwatch_requests_total[5m])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}