{
 "title": "IIS from WMI-Exporter",
 "description": "Monitor your IIS server with metrics coming from wmi_exporter.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(wmi_os_time,job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(wmi_iis_requests_total{job=~\"$job\"},instance)"
   },
   {
    "name": "app",
    "label": "Application",
    "query": "label_values(wmi_iis_current_application_pool_state{job=~\"$job\",instance=~\"$instance\"},app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wmi_iis_current_application_pool_state{app=~\"$app\",state=\"Running\"}"
    }
   ]
  },
  {
   "title": "Current Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wmi_iis_current_connections{site=~\"$app\"}"
    }
   ]
  },
  {
   "title": "No. of workers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wmi_iis_current_worker_processes{app=~\"$app\"}"
    }
   ]
  },
  {
   "title": "No. of process failures",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wmi_iis_recent_worker_process_failures{app=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Last Restart",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "wmi_iis_total_application_pool_start_time{app=~\"$app\"}*1000"
    }
   ]
  },
  {
   "title": "New Users",
   "type": "graph",
   "description": "Increase of anonymous users per 5m.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wmi_iis_anonymous_users_total{site=~\"$app\"}[5m])"
    }
   ]
  },
  {
   "title": "Data received",
   "type": "graph",
   "description": "Increase in data received by the application.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "increase(wmi_iis_received_bytes_total{site=~\"$app\"}[5m])/1024/1024"
    }
   ]
  },
  {
   "title": "Data sent",
   "type": "graph",
   "description": "Increase in data sent by the application.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "increase(wmi_iis_sent_bytes_total{site=~\"$app\"}[5m])/1024/1024"
    }
   ]
  },
  {
   "title": "Total requests by type",
   "type": "graph",
   "description": "Total requests divided by type of request.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wmi_iis_requests_total{site=~\"$app\"}[5m])"
    }
   ]
  }
 ]
}